# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='_user_fans_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
