# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('follow', 'Follow'), ('favorite', 'Favorite')], default='add', max_length=50),
        ),
    ]
