# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20170623_0914'),
        ('feeds', '0002_auto_20170627_0701'),
    ]

    operations = [
    ]
